name: youtube-downloader
services:
  - name: youtube-downloader
    ports:
      - port: 8000
        http:
          paths:
            - /
    env:
      - key: FLASK_ENV
        value: production
    docker:
      image: koyeb/app-youtube-downloader
